# Generated by Django 4.2.6 on 2023-10-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_library_image_library_author_image_and_more'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='course',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.library'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.library'),
        ),
    ]
