# Generated by Django 4.2.6 on 2023-10-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_authorimage_remove_library_author_image'),
        ('app', '0002_remove_author_author_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.authorimage'),
        ),
    ]
