# Generated by Django 4.2.6 on 2023-10-06 23:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='image',
        ),
        migrations.AddField(
            model_name='library',
            name='author_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='author_image'),
        ),
        migrations.AddField(
            model_name='library',
            name='course_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='course_image'),
        ),
    ]
