# Generated by Django 4.2.6 on 2023-10-06 23:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_library_image_library_author_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='author_image')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='library',
            name='author_image',
        ),
    ]
